import { alpha as a, palette as p, type HexColor } from './palette.js';

export const colors = {
  // Base
  focusBorder: a(p.gold, 0.6),
  foreground: p.fg,
  descriptionForeground: p.fgMuted,
  errorForeground: p.error,
  'widget.shadow': a(p.void, 0.5),
  'selection.background': a(p.violet, 0.35),
  'icon.foreground': p.fgMuted,
  'textLink.foreground': p.gold,
  'textLink.activeForeground': p.cyan,
  'textBlockQuote.background': p.bgRaised,
  'textBlockQuote.border': p.violet,
  'textCodeBlock.background': p.bgDeep,
  'textPreformat.foreground': p.gold,
  'textSeparator.foreground': p.border,

  // Title bar & window
  'titleBar.activeBackground': p.void,
  'titleBar.activeForeground': p.fgMuted,
  'titleBar.inactiveBackground': p.void,
  'titleBar.inactiveForeground': p.fgFaint,
  'titleBar.border': p.void,

  // Activity bar
  'activityBar.background': p.bgDeep,
  'activityBar.foreground': p.fg,
  'activityBar.inactiveForeground': p.fgFaint,
  'activityBar.activeBorder': p.gold,
  'activityBar.border': p.bgDeep,
  'activityBarBadge.background': p.violet,
  'activityBarBadge.foreground': p.void,

  // Side bar
  'sideBar.background': p.bgDeep,
  'sideBar.foreground': p.fgMuted,
  'sideBar.border': p.bgDeep,
  'sideBarTitle.foreground': p.fgMuted,
  'sideBarSectionHeader.background': p.bgDeep,
  'sideBarSectionHeader.foreground': p.fg,
  'sideBarSectionHeader.border': p.border,

  // Lists & trees
  'list.activeSelectionBackground': p.bgHigh,
  'list.activeSelectionForeground': p.fg,
  'list.inactiveSelectionBackground': p.bgRaised,
  'list.inactiveSelectionForeground': p.fg,
  'list.hoverBackground': p.bgRaised,
  'list.hoverForeground': p.fg,
  'list.focusOutline': a(p.gold, 0.5),
  'list.highlightForeground': p.gold,
  'list.errorForeground': p.error,
  'list.warningForeground': p.warning,
  'tree.indentGuidesStroke': p.border,

  // Editor groups & tabs
  'editorGroup.border': p.bgDeep,
  'editorGroupHeader.tabsBackground': p.bgDeep,
  'editorGroupHeader.tabsBorder': p.bgDeep,
  'tab.activeBackground': p.bg,
  'tab.activeForeground': p.fg,
  'tab.activeBorderTop': p.gold,
  'tab.inactiveBackground': p.bgDeep,
  'tab.inactiveForeground': p.fgFaint,
  'tab.border': p.bgDeep,
  'tab.hoverBackground': p.bgRaised,
  'tab.unfocusedActiveForeground': p.fgMuted,
  'tab.unfocusedActiveBorderTop': a(p.gold, 0.4),
  'tab.activeModifiedBorder': p.gold,
  'breadcrumb.foreground': p.fgFaint,
  'breadcrumb.focusForeground': p.fg,
  'breadcrumb.activeSelectionForeground': p.gold,
  'breadcrumbPicker.background': p.bgRaised,

  // Editor
  'editor.background': p.bg,
  'editor.foreground': p.fg,
  'editorCursor.foreground': p.gold,
  'editor.lineHighlightBackground': a(p.bgRaised, 0.8),
  'editor.lineHighlightBorder': '#00000000',
  'editorLineNumber.foreground': p.fgFaint,
  'editorLineNumber.activeForeground': p.gold,
  'editor.selectionBackground': a(p.violet, 0.1),
  'editor.inactiveSelectionBackground': a(p.violet, 0.06),
  'editor.selectionHighlightBackground': a(p.gold, 0.14),
  'editor.wordHighlightBackground': a(p.gold, 0.14),
  'editor.wordHighlightStrongBackground': a(p.gold, 0.24),
  'editor.findMatchBackground': a(p.gold, 0.18),
  'editor.findMatchBorder': p.gold,
  'editor.findMatchHighlightBackground': a(p.gold, 0.2),
  'editor.findRangeHighlightBackground': a(p.bgHigh, 0.6),
  'editor.rangeHighlightBackground': a(p.bgHigh, 0.5),
  'editor.hoverHighlightBackground': a(p.gold, 0.12),
  'editorBracketMatch.background': a(p.gold, 0.18),
  'editorBracketMatch.border': a(p.gold, 0.6),
  'editorBracketHighlight.foreground1': p.gold,
  'editorBracketHighlight.foreground2': p.ice,
  'editorBracketHighlight.foreground3': p.gold,
  'editorBracketHighlight.foreground4': p.rose,
  'editorBracketHighlight.foreground5': p.fg,
  'editorBracketHighlight.foreground6': p.cyan,
  'editorBracketHighlight.unexpectedBracket.foreground': p.error,
  'editorIndentGuide.background1': a(p.border, 0.8),
  'editorIndentGuide.activeBackground1': p.comment,
  'editorWhitespace.foreground': a(p.fgFaint, 0.4),
  'editorRuler.foreground': p.border,
  'editorCodeLens.foreground': p.fgFaint,
  'editorLink.activeForeground': p.gold,
  'editorInlayHint.background': a(p.bgHigh, 0.7),
  'editorInlayHint.foreground': p.fgMuted,
  'editorGhostText.foreground': a(p.fgMuted, 0.55),
  'editorError.foreground': p.error,
  'editorWarning.foreground': p.warning,
  'editorInfo.foreground': p.info,
  'editorHint.foreground': p.fgMuted,
  'editorUnnecessaryCode.opacity': '#000000aa',
  'editorOverviewRuler.border': p.bg,
  'editorOverviewRuler.errorForeground': p.error,
  'editorOverviewRuler.warningForeground': p.warning,
  'editorOverviewRuler.findMatchForeground': p.gold,
  'editorOverviewRuler.selectionHighlightForeground': p.gold,
  'editorGutter.background': p.bg,
  'editorGutter.addedBackground': p.added,
  'editorGutter.modifiedBackground': p.gold,
  'editorGutter.deletedBackground': p.error,

  // Minimap & scrollbar
  'minimap.background': p.bg,
  'minimap.selectionHighlight': a(p.violet, 0.5),
  'minimap.findMatchHighlight': p.gold,
  'minimapSlider.background': a(p.bgHigh, 0.5),
  'minimapSlider.hoverBackground': a(p.bgHigh, 0.7),
  'scrollbar.shadow': '#00000000',
  'scrollbarSlider.background': a(p.fgFaint, 0.25),
  'scrollbarSlider.hoverBackground': a(p.fgFaint, 0.4),
  'scrollbarSlider.activeBackground': a(p.violet, 0.4),

  // Widgets
  'editorWidget.background': p.bgRaised,
  'editorWidget.border': p.border,
  'editorHoverWidget.background': p.bgRaised,
  'editorHoverWidget.border': p.border,
  'editorSuggestWidget.background': p.bgRaised,
  'editorSuggestWidget.border': p.border,
  'editorSuggestWidget.foreground': p.fg,
  'editorSuggestWidget.highlightForeground': p.gold,
  'editorSuggestWidget.selectedBackground': p.bgHigh,
  'peekView.border': p.violet,
  'peekViewTitle.background': p.bgRaised,
  'peekViewEditor.background': p.bgDeep,
  'peekViewResult.background': p.bgRaised,
  'peekViewEditor.matchHighlightBackground': a(p.gold, 0.3),
  'peekViewResult.matchHighlightBackground': a(p.gold, 0.3),
  'peekViewResult.selectionBackground': p.bgHigh,

  // Inputs, buttons, dropdowns
  'input.background': p.bgDeep,
  'input.foreground': p.fg,
  'input.border': p.border,
  'input.placeholderForeground': p.fgFaint,
  'inputOption.activeBorder': p.gold,
  'inputOption.activeBackground': a(p.gold, 0.2),
  'inputValidation.errorBackground': p.bgRaised,
  'inputValidation.errorBorder': p.error,
  'button.background': p.gold,
  'button.foreground': p.void,
  'button.hoverBackground': p.brightGold,
  'button.secondaryBackground': p.bgHigh,
  'button.secondaryForeground': p.fg,
  'dropdown.background': p.bgRaised,
  'dropdown.border': p.border,
  'checkbox.background': p.bgDeep,
  'checkbox.border': p.border,
  'badge.background': p.bgHigh,
  'badge.foreground': p.fg,
  'progressBar.background': p.gold,

  // Quick input / command palette
  'quickInput.background': p.bgRaised,
  'quickInputList.focusBackground': p.bgHigh,
  'pickerGroup.foreground': p.gold,
  'pickerGroup.border': p.border,
  'keybindingLabel.background': p.bgHigh,
  'keybindingLabel.foreground': p.fg,
  'keybindingLabel.border': p.border,
  'keybindingLabel.bottomBorder': p.bgDeep,

  // Panel & terminal
  'panel.background': p.bgDeep,
  'panel.border': p.border,
  'panelTitle.activeForeground': p.fg,
  'panelTitle.inactiveForeground': p.fgFaint,
  'panelTitle.activeBorder': p.violet,
  'terminal.background': p.bgDeep,
  'terminal.foreground': p.fg,
  'terminalCursor.foreground': p.gold,
  'terminal.selectionBackground': a(p.violet, 0.3),
  'terminal.ansiBlack': p.bgHigh,
  'terminal.ansiRed': p.error,
  'terminal.ansiGreen': p.added,
  'terminal.ansiYellow': p.gold,
  'terminal.ansiBlue': p.ice,
  'terminal.ansiMagenta': p.violet,
  'terminal.ansiCyan': p.cyan,
  'terminal.ansiWhite': p.fgMuted,
  'terminal.ansiBrightBlack': p.fgFaint,
  'terminal.ansiBrightRed': p.error,
  'terminal.ansiBrightGreen': p.brightGreen,
  'terminal.ansiBrightYellow': p.brightGold,
  'terminal.ansiBrightBlue': p.brightIce,
  'terminal.ansiBrightMagenta': p.brightViolet,
  'terminal.ansiBrightCyan': p.cyan,
  'terminal.ansiBrightWhite': p.fg,

  // Debug sessions get a warm accretion-ring signal.
  'statusBar.background': p.void,
  'statusBar.foreground': p.fgMuted,
  'statusBar.border': p.void,
  'statusBar.debuggingBackground': p.gold,
  'statusBar.debuggingForeground': p.void,
  'statusBar.noFolderBackground': p.void,
  'statusBarItem.hoverBackground': p.bgHigh,
  'statusBarItem.remoteBackground': p.violet,
  'statusBarItem.remoteForeground': p.void,
  'statusBarItem.errorBackground': p.error,
  'statusBarItem.errorForeground': p.void,

  // Notifications
  'notifications.background': p.bgRaised,
  'notifications.foreground': p.fg,
  'notifications.border': p.border,
  'notificationCenterHeader.background': p.bgHigh,
  'notificationLink.foreground': p.gold,
  'notificationsErrorIcon.foreground': p.error,
  'notificationsWarningIcon.foreground': p.warning,
  'notificationsInfoIcon.foreground': p.info,

  // Git & diff
  'gitDecoration.addedResourceForeground': p.added,
  'gitDecoration.modifiedResourceForeground': p.gold,
  'gitDecoration.deletedResourceForeground': p.error,
  'gitDecoration.untrackedResourceForeground': p.added,
  'gitDecoration.ignoredResourceForeground': p.fgFaint,
  'gitDecoration.conflictingResourceForeground': p.rose,
  'diffEditor.insertedTextBackground': a(p.added, 0.15),
  'diffEditor.removedTextBackground': a(p.error, 0.18),
  'diffEditor.insertedLineBackground': a(p.added, 0.08),
  'diffEditor.removedLineBackground': a(p.error, 0.1),
  'merge.currentHeaderBackground': a(p.gold, 0.4),
  'merge.currentContentBackground': a(p.gold, 0.12),
  'merge.incomingHeaderBackground': a(p.gold, 0.4),
  'merge.incomingContentBackground': a(p.gold, 0.12),

  // Misc
  'debugToolBar.background': p.bgRaised,
  'menu.background': p.bgRaised,
  'menu.foreground': p.fg,
  'menu.selectionBackground': p.bgHigh,
  'menu.separatorBackground': p.border,
  'settings.headerForeground': p.fg,
  'settings.modifiedItemIndicator': p.gold,
  'welcomePage.tileBackground': p.bgRaised,
  'sash.hoverBorder': p.violet,
  'chat.requestBackground': p.bgRaised,
  'chat.slashCommandForeground': p.gold,
} satisfies Record<string, HexColor>;
